---
title: "NRT DataSENSE at Michigan Technological University"
---
# About DataSENSE at Michigan Technological University
DataSENSE is a NSF funded Research Traineeship (NRT) that aims to train PhD students to become leaders in the field of data science research. The program is designed to provide the necessary skills and knowledge to help develop professional skills. Through the use of workshops, DataSENSE provides opportunities for the trainees and members of the Michigan Tech community to learn about the tools and resourses used in research and apply them to their own research projects.

Below are the workshops that have been offered so far by DataSENSE. For more information, please visit the [DataSENSE website](https://www.mtu.edu/datasense/), or contact the DataSENSE team at [datasense-l@mtu.edu](mailto:datasense-l@mtu.edu).

# Workshops
## Workshops from Previous Academic Year
Spring 2026

- [Shell Workshop](https://lebrown.github.io/2026-02-19-mtu/): Learn about the Shell and how to use it
- [Reproducible Research Workshop](https://lebrown.github.io/2026-03-02-mtu/): Learn how to construct and run a reporoducible research study
- [Git Workshop](https://lebrown.github.io/2026-04-02-mtu/): Learn how to use git to host and manage version control for research projects

## Older Workshops
2024-2025 - No repositories available

- Remote Sensing - Nov. 21, 2024
- Exploring Drones - Feb. 19, 2025